In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from scipy import linalg as la

import pandas as pd

1\. **PCA on 3D dataset**

* Generate a dataset with 3 features each with N entries (N being ${\cal O}(1000)$). With $N(\mu,\sigma)$ the normali distribution with mean $\mu$ and $\sigma$  standard deviation, generate the 3 variables $x_{1,2,3}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues of the covariance matrix of the dataset
* Find the eigenvectors and eigenvalues using SVD. Check that the two procedures yield to same result
* What percent of the total dataset's variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained.
* Redefine the data in the basis yielded by the PCA procedure
* Plot the data points in the original and the new coordiantes as a set of scatter plots. Your final figure should have 2 rows of 3 plots each, where the columns show the (0,1), (0,2) and (1,2) proejctions.


In [2]:
#building the dataset

N = 1001


x1 = np.random.normal(0 , 1 , N)
x2 = x1 + np.random.normal(0 , 3 , N)
x3 = 2*x1 + x2

dataset= pd.DataFrame([x1,x2,x3])

dataset

0         1         2         3         4         5         6     \
0  0.649522 -0.528143  0.515729 -0.016445  0.271547  0.005411 -0.550662   
1 -2.199986  0.132862  0.556368  2.506049 -2.188040  3.033034 -3.835631   
2 -0.900941 -0.923425  1.587826  2.473160 -1.644946  3.043856 -4.936956   

       7         8         9     ...      991       992       993       994   \
0 -0.638948  1.298028  1.108897  ... -0.143433  0.796923  1.012933 -2.195479   
1 -1.273717  3.350775  3.021962  ... -7.263979 -0.170392 -0.784815 -5.349086   
2 -2.551613  5.946831  5.239755  ... -7.550845  1.423455  1.241050 -9.740043   

       995       996       997       998       999       1000  
0  0.975808 -0.216626 -2.141727 -1.120063 -1.435408 -1.033917  
1  0.022438  6.317535 -5.275158 -3.367713  3.177164 -1.558201  
2  1.974055  5.884282 -9.558613 -5.607838  0.306349 -3.626035  

[3 rows x 1001 columns]

In [3]:
#Find the eigenvectors and eigenvalues of the covariance matrix of the dataset

l, V = la.eig(np.cov(dataset))

print("Eighendecomposition\n")
print ("l = " ,  np.real_if_close(l) , '\n')
print ("V : \n" ,V)


#Find the eigenvectors and eigenvalues using SVD. Check that the two procedures yield to same result

U, spectrum, _ = la.svd(dataset)

print("\n ----------------------------------------- \n \n SVD procedure")
print ("\nSpectrum = " , spectrum**2/(N-1),'\n')
print ("VSVD : \n ",U,'\n')


print("-------------- \nChecking the result")

print("\n Eighenvalues")
print ("\nl = " ,  np.sort(np.real_if_close(l)))
print ("S(SVD) = " , np.sort(spectrum**2/(N-1)),'\n')

print("\n Eighenvectors")
print ("\nV :\n " ,  V)
print ("\nV (SVD) :\n " , U,'\n')

print("The eighenvalues are slightly different for the two computational methods, especially for the smallest one")
print("The eighenvectors are not perfectly equal, but really similar.")

Eighendecomposition

l =  [ 2.61238113e+01 -2.67359142e-16  1.85627817e+00] 

V : 
 [[-0.1230716  -0.81649658  0.56408041]
 [-0.56778299 -0.40824829 -0.71481173]
 [-0.8139262   0.40824829  0.4133491 ]]

 ----------------------------------------- 
 
 SVD procedure

Spectrum =  [2.62559827e+01 1.85647385e+00 1.25678688e-30] 

VSVD : 
  [[-0.12295371  0.56410612 -0.81649658]
 [-0.56793237 -0.71469305 -0.40824829]
 [-0.81383979  0.4135192   0.40824829]] 

-------------- 
Checking the result

 Eighenvalues

l =  [-2.67359142e-16  1.85627817e+00  2.61238113e+01]
S(SVD) =  [1.25678688e-30 1.85647385e+00 2.62559827e+01] 


 Eighenvectors

V :
  [[-0.1230716  -0.81649658  0.56408041]
 [-0.56778299 -0.40824829 -0.71481173]
 [-0.8139262   0.40824829  0.4133491 ]]

V (SVD) :
  [[-0.12295371  0.56410612 -0.81649658]
 [-0.56793237 -0.71469305 -0.40824829]
 [-0.81383979  0.4135192   0.40824829]] 

The eighenvalues are slightly different for the two computational methods, especially for the smallest o

In [4]:
#What percent of the total dataset's variability is explained by the principal components?
#Given how the dataset was constructed, do these make sense?
#Reduce the dimensionality of the system so that at least 99% of the total variability is retained.


Lambda = np.diag(np.real_if_close(l))


print(" Initlial dim p = 3 => new dim k = 1")
print ("\nPCA  k=1 (0):",abs(Lambda[0,0])/Lambda.trace(), "of the dataset's variability conserved")
print ("PCA  k=1 (1):",abs(Lambda[1,1])/Lambda.trace(), "of the dataset's variability conserved")
print ("PCA  k=1 (2):",abs(Lambda[2,2])/Lambda.trace(), "of the dataset's variability conserved")


print("\n \nInitlial dim p = 3 => new dim k = 2")
print ("\nPCA  k=2 (0,1):", abs(Lambda[0,0] + Lambda[1,1] )/Lambda.trace(), "of the dataset's variability conserved")
print ("PCA  k=2 (0,2):", abs(Lambda[0,0] + Lambda[2,2])/Lambda.trace(), "of the dataset's variability conserved")
print ("PCA  k=2 (1,2):", abs(Lambda[1,1] + Lambda[2,2])/Lambda.trace(), "of the dataset's variability conserved")


print("\nIt makes sense and the first component, as it is generated, conserves more variability")
print("To conserve the 99% of the variability, I perform PCA to dim k=2 using x1 and x3 as principal components")

 Initlial dim p = 3 => new dim k = 1

PCA  k=1 (0): 0.9336571755081209 of the dataset's variability conserved
PCA  k=1 (1): 9.555335494085437e-18 of the dataset's variability conserved
PCA  k=1 (2): 0.06634282449187906 of the dataset's variability conserved

 
Initlial dim p = 3 => new dim k = 2

PCA  k=2 (0,1): 0.9336571755081209 of the dataset's variability conserved
PCA  k=2 (0,2): 1.0 of the dataset's variability conserved
PCA  k=2 (1,2): 0.06634282449187905 of the dataset's variability conserved

It makes sense and the first component, as it is generated, conserves more variability
To conserve the 99% of the variability, I perform PCA to dim k=2 using x1 and x3 as principal components


In [5]:
#Redefine the data in the basis yielded by the PCA procedure

new_data = pd.DataFrame(np.dot(V.T , dataset))

#Plot the data points in the original and the new coordiantes as a set of scatter plots. 
#Your final figure should have 2 rows of 3 plots each,
#where the columns show the (0,1), (0,2) and (1,2) proejctions.

fig , ((ax1,ax2,ax3) , (ax4,ax5,ax6)) = plt.subplots(nrows=2, ncols=3, figsize=(15,10))

ax1.scatter(dataset.loc[0,:] , dataset.loc[1,:], alpha=0.55 , c='red', edgecolors='black')
ax1.set_xlim([-20,20])
ax1.set_ylim([-20,20])

ax2.scatter(dataset.loc[0,:] , dataset.loc[2,:], alpha=0.55, c='red', edgecolors='black')
ax2.set_xlim([-20,20])
ax2.set_ylim([-20,20])

ax3.scatter(dataset.loc[1,:] , dataset.loc[2,:], alpha=0.55, c='red', edgecolors='black')
ax3.set_xlim([-20,20])
ax3.set_ylim([-20,20])

ax4.scatter(new_data.loc[0,:] , new_data.loc[1,:], alpha=0.55, c='red', edgecolors='black')
ax4.set_xlim([-20,20])
ax4.set_ylim([-20,20])

ax5.scatter(new_data.loc[0,:] , new_data.loc[2,:], alpha=0.55, c='red', edgecolors='black')
ax5.set_xlim([-20,20])
ax5.set_ylim([-20,20])

ax6.scatter(new_data.loc[1,:] , new_data.loc[2,:], alpha=0.55, c='red', edgecolors='black')
ax6.set_xlim([-20,20])
ax6.set_ylim([-20,20])



(-20.0, 20.0)

2\. **PCA on a nD dataset**

Start from the dataset you have genereted in the previous exercise and add uncorrelated random noise. Such noise should be represented by other 10 uncorrelated variables normal distributed, with standar deviation much smaller (say, a factor 50) than those used to generate the $x_1$ and $x_2$.

Repeat the PCA procedure and compare the results with what you obtained before

In [6]:
noise = []

for i in range(10):
    noise.append(np.random.normal(0, 1/53 , N))
       
data2 = dataset.append(noise, ignore_index=True)

data2


0         1         2         3         4         5         6     \
0   0.649522 -0.528143  0.515729 -0.016445  0.271547  0.005411 -0.550662   
1  -2.199986  0.132862  0.556368  2.506049 -2.188040  3.033034 -3.835631   
2  -0.900941 -0.923425  1.587826  2.473160 -1.644946  3.043856 -4.936956   
3  -0.025482  0.031449  0.024899 -0.016483  0.012424 -0.003136  0.008191   
4   0.028861 -0.002619 -0.008018 -0.018446  0.009756  0.035077  0.006719   
5  -0.024175  0.024621  0.021629  0.004940 -0.020614  0.004024  0.005749   
6   0.008461  0.022477  0.018119  0.004682 -0.000398 -0.027222 -0.010914   
7   0.012083  0.027606 -0.020959  0.017083  0.028186 -0.007751 -0.023901   
8  -0.008947  0.010049 -0.015949 -0.028983 -0.016992 -0.004415 -0.036922   
9   0.033803 -0.016570 -0.005467  0.001918 -0.007441 -0.025773 -0.017231   
10  0.002438 -0.017643 -0.003099 -0.001124 -0.009502  0.033686 -0.020573   
11 -0.012923 -0.035235 -0.027730  0.037118  0.026496 -0.007574 -0.005161   
12 -0.007156  0.003115 -0.003978  0.010220 -0.032929 -0.026270  0.011896   

        7         8         9     ...      991       992       993       994   \
0  -0.638948  1.298028  1.108897  ... -0.143433  0.796923  1.012933 -2.195479   
1  -1.273717  3.350775  3.021962  ... -7.263979 -0.170392 -0.784815 -5.349086   
2  -2.551613  5.946831  5.239755  ... -7.550845  1.423455  1.241050 -9.740043   
3  -0.005964 -0.029406  0.016598  ... -0.017687  0.032774 -0.008489 -0.029641   
4   0.033634 -0.013249  0.012465  ... -0.002095 -0.009952 -0.010555  0.015223   
5   0.022663  0.015197  0.005089  ...  0.003210 -0.008154 -0.001512 -0.038987   
6  -0.021297 -0.002038  0.005241  ... -0.019229  0.014238  0.015059  0.003893   
7  -0.034719 -0.038589  0.020946  ...  0.009748  0.002482  0.010822 -0.019838   
8   0.016464  0.029173 -0.002228  ... -0.018578 -0.011787  0.004254 -0.036168   
9   0.034329 -0.016779  0.000110  ... -0.009835  0.012254  0.001546 -0.022646   
10  0.001907  0.044628 -0.007873  ... -0.007926 -0.012277  0.019954  0.017170   
11 -0.016275 -0.011080  0.031973  ...  0.013109  0.017191  0.003575  0.003873   
12 -0.016825  0.003403  0.015245  ...  0.002697  0.027078 -0.018917 -0.008117   

        995       996       997       998       999       1000  
0   0.975808 -0.216626 -2.141727 -1.120063 -1.435408 -1.033917  
1   0.022438  6.317535 -5.275158 -3.367713  3.177164 -1.558201  
2   1.974055  5.884282 -9.558613 -5.607838  0.306349 -3.626035  
3   0.010438  0.025221 -0.021857 -0.005314  0.009276  0.008408  
4   0.001042 -0.002340  0.007688 -0.001859  0.000716  0.014737  
5  -0.019121  0.008683 -0.001180 -0.008720  0.030581  0.029758  
6   0.009736 -0.005579  0.009501 -0.015943 -0.006738  0.000927  
7   0.031167  0.031753 -0.004206  0.009122 -0.026852  0.002989  
8   0.005012  0.008245  0.006391 -0.019167 -0.001747 -0.005470  
9   0.000078 -0.022221 -0.003067  0.004081 -0.014234 -0.013022  
10 -0.004994  0.002580 -0.001304 -0.010697 -0.020983  0.019352  
11  0.001298 -0.001378  0.027766 -0.009104 -0.018628  0.001964  
12  0.016212 -0.005346  0.021732  0.000530  0.011050 -0.012033  

[13 rows x 1001 columns]

In [7]:
l2, V2 = la.eig(np.cov(data2))

Lambda2 = np.diag(np.real_if_close(l2))

print("\nVariability conserved component by component: \n", np.real_if_close(l2)/np.trace(Lambda2))

print ("\nPCA  k=2 (0,1):", abs(Lambda2[0,0] + Lambda2[1,1] )/Lambda2.trace(), "of the dataset's variability conserved")

print("\nThe two principal variables are the first and the second ones.")
print("Variability of the noise is neglectable; being uncorrelated it has less meaning in the analysis")


Variability conserved component by component: 
 [9.33539479e-01 6.63346702e-02 2.09626670e-17 1.48323375e-05
 1.09215799e-05 1.38322572e-05 1.32991963e-05 1.33637356e-05
 1.14052534e-05 1.24583877e-05 1.16907628e-05 1.21149855e-05
 1.19322317e-05]

PCA  k=2 (0,1): 0.9998741492722725 of the dataset's variability conserved

The two principal variables are the first and the second ones.
Variability of the noise is neglectable; being uncorrelated it has less meaning in the analysis


3 \. **Looking at an oscillating spring** (optional)

Imagine you have $n$ cameras looking at a spring oscillating along the $x$ axis. Each  camera record the motion of the spring looking at it along a given direction defined by the pair $(\theta_i, \phi_i)$, the angles in spherical coordinates. 

Start from the simulation of the records (say ${\cal O}(1000)$) of the spring's motion along the x axis, assuming a little random noise affects the measurements along the $y$. Rotate such dataset to emulate the records of each camera.

Perform a Principal Component Analysis on the thus obtained dataset, aiming at finding the only one coordinate that really matters.


In [8]:
n = 1001

t0=0
dt=0.1
#omega=1

x=[np.cos(t0+dt*i) for i in range(n)]

y=np.random.normal(0, 0.01 , n)  #y0 setted = 0

z=np.zeros(n)

fig = plt.figure(figsize = (10,10))
ax = fig.add_subplot(projection='3d')
ax.scatter(x, y, z , alpha=0.55, c='red', edgecolors='black')
ax.set_title("Oscillating Spring with random noise on y" , fontsize=20)
ax.set_xlabel("x" , fontsize=16)
ax.set_ylabel("y", fontsize=16)
ax.set_zlabel("z", fontsize=16)
plt.show()

In [9]:
def camera(theta,phi):
    
    rot_y = np.array( [ [np.cos(theta) , 0 , np.sin(theta)] , [0 , 1 , 0] , [-np.sin(theta), 0 , np.cos(theta) ]])
    rot_z = np.array( [ [np.cos(phi) , -np.sin(phi) , 0] , [np.sin(phi) , np.cos(phi) , 0] , [0, 0 , 1] ])
    
    return rot_y.dot(rot_z)



#example of rotation

rotation = camera(np.pi/3 , np.pi/3).dot(np.array([x,y,z]))

fig = plt.figure(figsize = (10,10))
ax = fig.add_subplot(projection='3d')

ax.scatter(rotation[0], rotation[1], rotation[2] , alpha=0.55, c='orange', edgecolors='black')

ax.set_title("Rotated Spring " , fontsize=20)
ax.set_xlabel(" x' " , fontsize=16)
ax.set_ylabel(" y' ", fontsize=16)
ax.set_zlabel(" z' ", fontsize=16)

plt.show()

In [10]:
#building dataset

in_pos=np.array([x,y,z])

n_cameras=11

theta_rot= np.random.uniform(0 , np.pi, n_cameras)
phi_rot= np.random.uniform(0, 2*np.pi , n_cameras)

views=[]
for t, p in zip(theta_rot , phi_rot):
    views.append( camera(t,p).dot(in_pos) )

dataset_list = ([x,y,z])

for v in views:
    for i in range(3):
        dataset_list.append(v[i])

dataset_spring=pd.DataFrame(dataset_list)
    
    
#performing PCA    
lr, Vr = la.eig(np.cov(dataset_spring))

LambdaR = np.diag(np.real_if_close(lr))

print("\nVariability conserved component by component: \n \n", np.real_if_close(lr)/np.trace(LambdaR))


Variability conserved component by component: 
 
 [ 9.99795734e-01  2.04265512e-04  9.49631009e-17 -9.10374638e-17
  7.81990313e-17  7.24198767e-17  5.98308897e-17 -5.82337753e-17
 -5.82337753e-17 -4.77493053e-17  4.06536132e-17 -8.15329210e-19
 -8.15329210e-19 -3.03352257e-17 -3.03352257e-17  2.85291671e-17
  2.02222063e-17 -1.83201344e-17  1.27900429e-17  1.12981955e-17
 -1.04636674e-17  5.60468380e-18  2.05395201e-18  2.05395201e-18
 -7.76905292e-18 -6.52756646e-18 -4.78257506e-18 -3.43684060e-18
  2.76892237e-18  5.55572168e-19  5.55572168e-19 -5.88009546e-19
  7.59189908e-20 -1.77086937e-20 -1.77086937e-20  0.00000000e+00]


To cover more than the 90% of the dataset's variability the first component is enough. 
In fact, as the simulation is generated, the most important component (the one that is the most meaningful for the analysis) is the first one, i.e. the one that contains the view of the x axis. 

4\. **PCA on the MAGIC dataset** (optional)

Perform a PCA on the magic04.data dataset

In [11]:
# get the dataset and its description on the proper data directory
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data -P /home/ilazza/LaboratoryOfComputationalPhysics_Y4/dataEs7/
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.names -P /home/ilazza/LaboratoryOfComputationalPhysics_Y4/dataEs7/

--2021-12-13 08:41:49--  https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data
Risoluzione di archive.ics.uci.edu (archive.ics.uci.edu)... non riuscito: Nome o servizio sconosciuto.
wget: impossibile risolvere l'indirizzo dell'host «archive.ics.uci.edu»
--2021-12-13 08:41:49--  https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.names
Risoluzione di archive.ics.uci.edu (archive.ics.uci.edu)... non riuscito: Nome o servizio sconosciuto.
wget: impossibile risolvere l'indirizzo dell'host «archive.ics.uci.edu»


In [12]:
file_name='/home/ilazza/LaboratoryOfComputationalPhysics_Y4/dataEs7/magic04.data'
dataf=pd.read_csv( file_name, index_col=False)

labels=['fLength' ,'fWidth' , 'fSize', 'fConc', 'fConc1' , 'fAsym' , 'fM3Long', 'fM3Trans' , 'fAlpha', 'fDist', 'class']

dataf.columns = labels

dataf

fLength    fWidth   fSize   fConc  fConc1     fAsym   fM3Long  \
0       31.6036   11.7235  2.5185  0.5303  0.3773   26.2722   23.8238   
1      162.0520  136.0310  4.0612  0.0374  0.0187  116.7410  -64.8580   
2       23.8172    9.5728  2.3385  0.6147  0.3922   27.2107   -6.4633   
3       75.1362   30.9205  3.1611  0.3168  0.1832   -5.5277   28.5525   
4       51.6240   21.1502  2.9085  0.2420  0.1340   50.8761   43.1887   
...         ...       ...     ...     ...     ...       ...       ...   
19014   21.3846   10.9170  2.6161  0.5857  0.3934   15.2618   11.5245   
19015   28.9452    6.7020  2.2672  0.5351  0.2784   37.0816   13.1853   
19016   75.4455   47.5305  3.4483  0.1417  0.0549   -9.3561   41.0562   
19017  120.5135   76.9018  3.9939  0.0944  0.0683    5.8043  -93.5224   
19018  187.1814   53.0014  3.2093  0.2876  0.1539 -167.3125 -168.4558   

       fM3Trans   fAlpha     fDist class  
0       -9.9574   6.3609  205.2610     g  
1      -45.2160  76.9600  256.7880     g  
2       -7.1513  10.4490  116.7370     g  
3       21.8393   4.6480  356.4620     g  
4        9.8145   3.6130  238.0980     g  
...         ...      ...       ...   ...  
19014    2.8766   2.4229  106.8258     h  
19015   -2.9632  86.7975  247.4560     h  
19016   -9.4662  30.2987  256.5166     h  
19017  -63.8389  84.6874  408.3166     h  
19018   31.4755  52.7310  272.3174     h  

[19019 rows x 11 columns]

In [13]:
#reading magic.name , class h is background

dataf = dataf[dataf['class'] == "g"]
dataf = dataf.drop(['class'] , axis=1)


#reshaping and doing things to perform PCA

dataset=dataf.to_numpy()
dataset = dataset.reshape((dataset.shape[1], dataset.shape[0]))

dataset

array([[ 3.16036e+01,  1.17235e+01,  2.51850e+00, ...,  1.96670e+00,
         2.86609e+02,  4.88751e+01],
       [ 1.94472e+01,  3.06430e+00,  2.45800e-01, ...,  4.24215e+02,
         1.24992e+01,  1.19681e+01],
       [ 2.03940e+00,  6.94100e-01,  3.51600e-01, ...,  2.27090e+01,
         4.30000e-03,  2.20280e+00],
       ...,
       [ 1.21093e+01,  8.17696e+01,  1.12872e+02, ...,  2.82344e+01,
         3.30502e+01,  7.50990e+00],
       [ 6.61000e+00,  2.35973e+02,  3.19610e+01, ..., -1.99657e+01,
         1.17531e+01,  2.28802e+01],
       [ 1.26280e+02,  2.45973e+01,  1.52460e+01, ..., -1.20726e+01,
         1.75809e+01,  1.71227e+02]])

In [14]:
#performing PCA   

lmagic, Vmagic = la.eig(np.cov(dataset[:,:1000]))

LambdaMagic = np.diag(np.real_if_close(lmagic))
sortedL_magic= - np.sort( - np.real_if_close(lmagic))


PCA = sortedL_magic/np.trace(LambdaMagic)
print("\n PCA Variability conserved component by component: \n \n", PCA)
print('\n ')
variability = 0

for k in range(1, len(PCA)+1):
    
    variability = PCA[:k].sum()
    
    if variability > 0.9 :
        print("PCA works good and can reduce from " , len(PCA) , " to k = ", k, " components , with a variability of", variability)
        break
        
    elif k == len(PCA)-1:
        print("PCA failed, max variability reached is ", variability, "with", k, "components of", len(PCA))




 PCA Variability conserved component by component: 
 
 [0.16645484 0.16515049 0.11828735 0.10941359 0.09769913 0.09561794
 0.08052453 0.07916915 0.06578007 0.0219029 ]

 
PCA works good and can reduce from  10  to k =  8  components , with a variability of 0.9123170293841735
